config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:edit, :update, :show]
  resources :activities do
    resources :reviews, only: [:create, :new]
    resources :reservations, only: [:create, :new]
  end
  resources :reviews, only: :destroy
  resources :reservations, only: :destroy
end

app/models/activity.rb
class Activity < ApplicationRecord
  CATEGORY = %w(land sea indoor virtual)
  has_many_attached :photos
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :address, presence: true
  validates :title, presence: true
  validates :short_description, presence: true
  validates :details, presence: true
  validates :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :title, :details, :category],
    associated_against: {
      user: [ :username, :email ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :activity
  belongs_to :user

  validates :number_of_people, inclusion: { in: %w(10..50)} , numericality: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  RATING = [0, 1, 2, 3, 4, 5]
  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_one_attached :banner
  has_many :activities
  has_many :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @activities = Activity.global_search(params[:query])
    else
      @activities = Activity.all
    end
    # @markers = @activities.geocoded.map do |activity|
    #   {
    #     lat: activity.latitude,
    #     lng: activity.longitude
    #   }
    # end
  end

  def show
    @marker = [{
      lat: @activity.latitude,
      lng: @activity.longitude
    }]
    @review = Review.new
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def activity_params
    params.require(:activity).permit(:details, :price, :address, :title, :category, :latitude, :short_description, :longitude, photos: [])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_activity, only: [:new, :create]


  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.activity = @Activity
    @reservation.user = current_user
    @review = Review.new
    if @reservation.save
      redirect_to activity_path(@activity)
    else
      render 'activities/show'
    end
  end

  def destroy
    @reservation = reservation.find(params[:id])
    @reservation.destroy
    redirect_to activity_path(@reservation.activity)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :number_of_people)
  end

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_activity, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.activity = @activity
    @review.user = current_user
    if @review.save
      redirect_to activity_path(@activity)
    else
      render 'activities/show'
    end
  end

  def destroy
    @review =review.find(params[:id])
    @review.user.id = current_user.id
    @review.destroy
    redirect_to activity_path(@review.activity)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :about_me, :first_name, :last_name, :banner, :username)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 col-md-4">
      <%= simple_form_for @activity do |f| %>
        <%= f.input :title %>
        <%= f.input :short_description %>
        <%= f.input :details %>
        <%= f.input :address %>
        Categories:
        <%= f.select :category, Activity::CATEGORY %>
        <%= f.input :price %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }%>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<%= render "form", activity: @activity %>

app/views/activities/index.html.erb
<div class="bannerindex" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1521336575822-6da63fb45455?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1><strong>Our currated selection of activities
    </strong></h1>
  </div>
</div>

<div class="containersearch">
  <div class="row">
      <%= form_tag activities_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control p-2",
          placeholder: "Find an activity"
        %>
        <%= submit_tag "Search", class: "btn btn-primary p-2" %>
      <% end %>
  </div>
</div>

<div class="grid-container1">
  <% @activities.each do |activity| %>
    <div class="grid-item">
      <%= link_to activity_path(activity), class:"img1-hover-zoom" do%>
      <div class="card-activity">
        <%= cl_image_tag activity.photos[0].key%>
        <div class="card-activity-infos">
          <div class="card-activity-description">
            <h2><%= activity.title %></h2>
            <p><%= activity.short_description %></p>
          </div>
          <h2 class="card-activity-pricing"><%= activity.address%><br> Rs:<%= activity.price %></h2>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/activities/new.html.erb
<%= simple_form_for @activity do |f| %>
  <%= f.input :details %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/activities/show.html.erb
<div class="card_preview">
  <p class="info"><%= @activity.title %></p>
  <p><%= @activity.details %></p>
  <p class="info">Rs. <%= @activity.price %></p>
  <p class="info"><%= @activity.address %></p>
  <div class="photos_container">
    <div class="photos_container1">
      <%= cl_image_tag @activity.photos[0].key%>
    </div>
    <div class="photos_container2">
      <% @activity.photos.drop(1).each do |photo| %>
        <%= cl_image_tag photo.key,class:"sidephotos col", style:"width:350px; height:300px;" %>
      <% end %>
    </div>
  </div>
</div>

<% if current_user %>
  <% link_to 'Leave a review', new_activity_review_path(@activity) %>
    <% if @activity.user.id == current_user.id %>
      <%= link_to("Edit", edit_activity_path(@activity)) %>
      <%= link_to "Delete", activity_path(@activity), method: :delete, data: { confirm: "Are you sure?"} %>      <% end %>
    <% end %>
<br>
<br>

    <div class="btn-flat btn-small">
      <%= link_to("Book activity", new_activity_reservation_path(@activity)) %>
    </div>
    <br>

    <h1><strong>Reviews</strong></h1>
          <ul class="list-group">
          <% @activity.reviews.each do |review| %>
            <li class="list-group-item"><%= review.comment %></li>
            <li class="list-group-item"><%= '⭐' * review.rating %></li>
            <br>
          <% end %>
        </ul>
        <p>Please leave a comment:</p>
        <%= simple_form_for [ @activity, @review ] do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: 0..5 %>
          <br>
          <%= f.submit "Submit review", class: "btn btn-primary" %>
        <% end %>
        <br>
        <%= link_to("Back to activities", activities_path) %>



    </div>

    <div style="width: 100%; height: 500px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @marker.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiBonPlan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://teambuilding.mu/images/gallery/1_KanJam_Fun_Outdoor_Team_Bonding.jpg);">
  <div class="container">
    <h1><strong>Events to Engage,
    </strong></h1>
    <br>
    <h1><strong>
    Connect and Inspire.
    </strong></h1>
    <br>
    <h1><strong>
    In person or virtual!</strong></h1>
    <br>
    <a class="btn btn-flat btn-banner btn-lg" href="/activities"><strong>Explore</strong></a>
  </div>
</div>
<br>
<br>

<div class="container1 mb-5">
  <h2 style="text-align: center;">Boost morale and maintain</h2>
    <h2 style="text-align: center;">a sense of comradery among colleagues, no matter</h2>
    <h2 style="text-align: center;">where they’re located.</h2>

    <div class="d-flex justify-content-around">
      <div class="d-flex justify-content-space-around">
        <div class="d-flex flex-column">
          <%= image_tag "iconpeople.svg", :class=>"p-2", :style =>"height: 5.5rem;" %>
          <p class="p-2">Suitable for</p>
          <p >any group size</p>
        </div>
        &nbsp;
        &nbsp;
        &nbsp;
        &nbsp;
        &nbsp;
        <div class="d-flex flex-column">
          <%= image_tag "virtuallogo.svg", :class=>"p-2", :style =>"height: 5.5rem;" %>
          <p class="p-2">20+ VR Activities for Remote</p>
          <p> &nbsp; &nbsp; &nbsp; &nbsp;& In-Person Teams</p>
        </div>
        &nbsp;
        &nbsp;
        &nbsp;
        &nbsp;
        &nbsp;
        <div class="d-flex flex-column">
          <%= image_tag "piggylogo.svg", :class=>"p-2", :style =>"height: 5.5rem;" %>
          <p class="p-2">Flexible Options</p>
          <p>&nbsp; for Any Budget</p>
        </div>
      </div>
    </div>
</div>

<%# <div class="container containerhome mb-5">

</div> %>

<div class="containerhome">
  <h2><strong>Explore Activities by Category:</strong></h2>
  <br>
</div>

<div class="d-flex justify-content-around containerhome">
  <%= link_to controller: "activities", query: "Land" do%>
    <div class="card-home img-hover-zoom" style="width: 18rem; height: 18rem;">
        <%= image_tag "land.png" %>
      <div class="card-body card-body-home">
        <h5 class="card-title"><strong>Land Activities</strong></h5>
        <p class="card-text">Discover all the best land activities.</p>
      </div>
    </div>
  <% end %>

  <%= link_to controller: "activities", query: "Sea" do%>
    <div class="card-home img-hover-zoom" style="width: 18rem; height: 18rem;">
      <%= image_tag "sea.png" %>
      <div class="card-body card-body-home">
        <h5 class="card-title"><strong>Sea Activities</strong></h5>
        <p class="card-text">We offer some of the best water sports activities.</p>
      </div>
    </div>
  <% end %>

  <%= link_to controller: "activities", query: "Indoor" do%>
    <div class="card-home img-hover-zoom" style="width: 18rem; height: 18rem; border-radius: 16px">
      <%= image_tag "indoor.jpg" %>
      <div class="card-body card-body-home">
        <h5 class="card-title"><strong>Indoor Activities</strong></h5>
        <p class="card-text">Browse through our fine selection of indoor activities</p>
      </div>
    </div>
  <% end %>

  <%= link_to controller: "activities", query: "Virtual" do%>
    <div class="card-home img-hover-zoom" style="width: 18rem; height: 18rem;">
      <%= image_tag "vr.png" %>
      <div class="card-body card-body-home">
        <h5 class="card-title"><strong>VR Activities</strong></h5>
        <p class="card-text">Try our brand new VR activities. You gonna get your mind blown!</p>
      </div>
    </div>
  <% end %>
</div>





<%# <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div>
<br>
<br> %>
<br>
<br>
<br>
<br>

<div class="bannercard" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.klook.com/image/upload/c_fill,w_1160,h_460,f_auto/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/txtjklx3bjrewkzqmeob.webp);">
  <div class="container containerbanner">
  <br>
    <h1><strong>Not sure which
    </strong></h1>
    <h1><strong>activities to do?  Perfect!
    </strong></h1>
    <br>
    <% x = Activity.first.id%>
    <% y = Activity.last.id%>
    <% arr = (x..y).to_a.sample %>
    <a class="btn btn-flat btn-banner" href='/activities/<%= arr %>'><strong>Take a leap of faith!</strong></a>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 col-md-4">
     <%= simple_form_for [ @activity, @reservation ] do |f| %>
      <%= f.input :number_of_people %>
      <%= f.input :date,
        :as => :date %>
      <%= f.submit "Book reservation", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the team Anubatir
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag 'Logo.png' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create an activity", new_activity_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.avatar.key %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
              <%= image_tag "https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "View My profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 col-md-4">
      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :username %>
        <%= f.input :about_me %>
        <%= f.input :avatar, as: :file%>
        <%= f.input :banner, as: :file%>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.banner.key %>
  <div class="bannerprofile" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @user.banner.key %>')">
  </div>
<% else %>
<div class="bannerprofile" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://i.pinimg.com/originals/21/3f/13/213f13131ea438cb95ac5fcad21d0bb2.jpg')">
</div>
<% end %>

<% if @user.avatar.key %>
  <%= cl_image_tag (@user.avatar.key), class:"picavatar"%>
<% else %>
  <%= image_tag "https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png", class:"picavatar" %>
<% end %>

<div class="col-md-8">
              <div class="card mb-3" style="postion: relative; top:25vh; left: 15px; background-color: transparent; border: transparent;">
                <div class="card-body" style="postion: relative; top: 28vh; left: -431px">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.first_name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.last_name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.username %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">About me</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.about_me %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Activities Booked</h6>
                    </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12 btn btn-info">
                      <%= link_to("Edit", edit_user_path(@user))%>
                    </div>
                  </div>
                </div>
              </div>